project_id = "mgvnlwcuvwwijoynuohi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.web-scraper]
verify_jwt = false

[auth]
enabled = true
port = 54328
external_url = "http://127.0.0.1:54328"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_change_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[storage]
enabled = true
port = 54329
file_size_limit = "50MiB"
image_transformation_enabled = true

[edge-runtime]
enabled = true
port = 54330
ip_version = "ipv4"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"