
import React from 'react';
import DepartmentTemplate from '@/components/DepartmentTemplate';

const AIDSDepartment = () => {
  const departmentData = {
    name: "Artificial Intelligence & Data Science",
    vision: "To be a leading centre for education, research, and innovation in artificial intelligence and data science and to prepare students to be ethical and responsible leaders in the field of artificial intelligence and data science.",
    mission: [
      "To provide students with a world-class education in artificial intelligence and data science.",
      "To conduct cutting-edge research in artificial intelligence and data science.",
      "To promote ethical and responsible use of artificial intelligence and data science.",
      "To prepare students for successful careers in artificial intelligence and data science.",
      "To collaborate with industry and academia to solve real-world problems using artificial intelligence and data science."
    ],
    programOutcomes: [
      { code: "PO1", title: "Engineering knowledge", code2: "PO7", title2: "Environment and sustainability" },
      { code: "PO2", title: "Problem analysis", code2: "PO8", title2: "Ethics" },
      { code: "PO3", title: "Design/Development of Solutions", code2: "PO9", title2: "Individual and TeamWork" },
      { code: "PO4", title: "Conduct Investigation of Complex Problems", code2: "PO10", title2: "Communication Skills" },
      { code: "PO5", title: "Modern Tool Usage", code2: "PO11", title2: "Project Management and Finance" },
      { code: "PO6", title: "The Engineer and Society", code2: "PO12", title2: "Life-long Learning" }
    ],
    programEducationOutcomes: [
      "Graduates Will Have The Capabilities To Apply AI&DS Knowledge To Develop Feasible Systems.",
      "Graduates Will Be Able To Handle The Challenges Of Rapidly Changing Technology.",
      "Equip The Graduates With Strong Technical Knowledge, Competency In Soft Skills, Lifelong Learning Skills That Allow Them To Contribute Ethically To The Need Of Society."
    ],
    programSpecificOutcomes: [
      "Professional Skills-The ability to understand, analyse and develop computer programs in the areas related to algorithms, system software, multimedia, web design, networking, artificial intelligence and data science for efficient design of computer-based systems of varying complexities.",
      "Problem-Solving Skills- The ability to apply standard practices and strategies in software project development using open-ended programming environments to deliver a quality product for business success.",
      "Successful Career and Entrepreneurship- The ability to employ modern computer languages, environments and platforms in creating innovative career paths to be an entrepreneur and to have a zest for higher studies."
    ],
    hod: {
      name: "Prof. Anil V. Walke",
      position: "HOD & Assistant Professor",
      qualification: "PhD*, ME E&TC, PICT Pune",
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
      message: [
        "Welcome to the Department of Artificial Intelligence and Data Science at ISBM College of Engineering, Nande, Pune.",
        "Artificial Intelligence and Data Science is an interdisciplinary branch of science, engineering and technology creating a complete ecosystem and a paradigm shift in virtually every sector of the technical industry, academics and research. Artificial Intelligence and Data Science is the future of technology which are changing the world at very high pace.",
        "The basic objectives of this course is to train students with the next age of Intelligence and analytics generated by machines, influencing nearly every facet of our lives to help improve efficiencies and augment human capabilities, influencing consumer products with significant breakthroughs in healthcare, manufacturing, finance and retail industries.",
        "With the tremendous amount of data generated every day and the computing power available, Data Science plays important role helping every business organisation in identifying business trends and changes through advanced Big Data Analytics with variety of techniques and tools to interpret and predict business results and future from multiple data sources through statistical analysis, data aggregation, and data mining.",
        "The department of Artificial Intelligence & Data Science (AI & DS) is established in the academic year 2020-2021. This is a 4-year degree course approved by AICTE, New Delhi under Savitribai Phule Pune University (SPPU). The Department has experienced faculty members/staff and the state of art research laboratories. The curriculum of AI & DS is prescribed by SPPU.",
        "This curriculum targets technical and design skills, AI knowledge, and competencies needed to master strategic analytical methods and tools, and data management, with the objective of creating innovative strategies to solve challenging real-world problems.",
        "The department has very good connect with industries. The objective of this course is to make students ready for industry with practical exposure in AI & DS."
      ]
    },
    facultyMembers: [
      { name: "Prof. Anil V. Walke", position: "HOD & Assistant Professor", qualification: "PhD*, ME(E&TC), BE(E&TC), Industry: 10 Years, Academic: 18 Years", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof. Suwarna Karankal", position: "Assistant Professor", qualification: "PhD*, M.E. Computer Engineering, B.E. Computer Engineering, Academic: 14.8 Years", photo: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof. Snehal Javheri", position: "Assistant Professor", qualification: "M.E. (Computer Engineering), B.E. (Computer Engineering), Academic: 12.5 Years", photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof. Nikita Khawase", position: "Assistant Professor", qualification: "M.Tech (CSE), B.E. (IT), Academic: 6 Years", photo: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof. Tejaswini Ganesh Mali", position: "Assistant Professor", qualification: "M.E. (Computer Engineering), B.E. (Computer Engineering), Academic: 6 Years", photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof. Dipti Jaisinghani", position: "Assistant Professor", qualification: "BE (Electronics), ME (EnTC), VLSI & Embedded Systems, Academic: 10 Years", photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof Azhar Inamdar", position: "Assistant Professor", qualification: "M.Tech (IT), B.Tech (Computer Engineering), Academic: 3 Years", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof Shradha Mukkawar", position: "Assistant Professor", qualification: "M.E (Computer Science), B.E. (CS), Academic: 1 Year", photo: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof. Balbhim Lanke", position: "Assistant Professor", qualification: "ME (Data Science), BE (IT), Industry: 2.5 Years, Academic: 1 Year", photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face" },
      { name: "Prof. Poonam Mishra", position: "Assistant Professor", qualification: "ME (CSE), BE (CSE), Academic: 1 Year", photo: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face" },
      { name: "Mrs. Nita Lahulkar", position: "Technical Assistant", qualification: "B.E(IT), Academic: 1 Year", photo: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face" }
    ],
    activities: [
      { title: "Data Structure and Analytics Lab", description: "Advanced data structure implementation and analytics", color: "from-blue-50 to-blue-100 text-blue-800" },
      { title: "Object Oriented Programming Lab", description: "Hands-on programming with OOP concepts", color: "from-green-50 to-green-100 text-green-800" },
      { title: "Data Visualization Lab", description: "Creating meaningful visualizations from data", color: "from-purple-50 to-purple-100 text-purple-800" },
      { title: "Natural Language Processing Lab", description: "Text processing and language understanding", color: "from-orange-50 to-orange-100 text-orange-800" },
      { title: "Research Projects", description: "Student research in AI and Data Science", color: "from-pink-50 to-pink-100 text-pink-800" },
      { title: "Industry Partnerships", description: "Collaborations with tech companies", color: "from-indigo-50 to-indigo-100 text-indigo-800" }
    ]
  };

  return <DepartmentTemplate data={departmentData} />;
};

export default AIDSDepartment;
