// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgvnlwcuvwwijoynuohi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndm5sd2N1dnd3aWpveW51b2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjcwODksImV4cCI6MjA2NTE0MzA4OX0.Pb6WwM4Yd6kpTfyHDEAc9eE3QHW1PqcjREJukvpmyPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});